blank_issues_enabled: false
contact_links:
  - name: KTP Github
    url: https://github.com/lynxplay/ktp
    about: If you are having issues with timings or have other minor issues, come ask us on our Discord server!
